name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'
  schedule:
    - cron: '0 0 * * *'
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
        - ubuntu-latest
        - windows-latest
        - macos-latest
        python:
        - 3.6
        - 3.7
        - 3.8
        - 3.9
        - '3.10'
    steps:
    - uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
    - name: install
      run: pip3 install --user --upgrade -r requirements.txt pip tox -e .
    - name: test
      run: python3 -m tox -p all
  distribute:
    if: github.ref == 'refs/heads/master'
    needs:
      - test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: install
      run: pip3 install --user --upgrade -r requirements.txt pip tox -e .
    - name: distribute
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: python3 scripts/update_gcp_prefix_format_list.py && daves-dev-tools distribute --skip-existing
