name: Test, Update GCP Prefix Format List, and Distribute to PYPI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: '0 0 * * *'
jobs:
  test-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        python: [3.6, 3.7, 3.8, 3.9, '3.10']
    steps:
    - uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
    - name: Install
      run: pwd
      run: echo %cd%
      run: python3 -m venv venv
      run: venv/bin/pip3 install -r requirements.txt -e .
    - name: Tox
      run: venv/bin/tox -r -p
  test-ubuntu:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.6, 3.7, 3.8, 3.9, '3.10']
    steps:
    - uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
    - name: Install
      run: make
    - name: Tox
      run: venv/bin/tox -r -p
  distribute:
    needs:
      - test-ubuntu
      - test-windows
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install
      run: make
    - name: Build and Publish
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: venv/bin/daves-dev-tools distribute --skip-existing

